name: Build and Tag Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Tag Docker Image
      id: build-image
      run: |
        IMAGE_NAME=raiveton/2048
        VERSION=$(date +%Y%m%d.%H%M%S) # Generate a timestamp-based version tag
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        docker build -t $IMAGE_NAME:$VERSION .

    - name: Push Docker Image
      run: |
        IMAGE_NAME=my-docker-image
        docker push $IMAGE_NAME:$VERSION
